library(dplyr)
library(ggplot2)
setwd(out_dir)
pca_coord <- read.csv("/mnt/storage13/nbillows/Pf_09_24/dummy/checking_all_FST_paired_2024_11_12/pca_coordinates.csv", header=TRUE)
PCs <- paste0("PC", 1:10)
colnames(pca_coord) <- c("X", PCs, "wgs_id")
metadata <- read.csv("/mnt/storage13/nbillows/Pf_09_24/dummy/dummy.tsv", sep="\t", header=TRUE)
pca_coord <- left_join(pca_coord, metadata)
ggplot(pca_coord, aes(x=PC1, y=PC2, color=Country)) + geom_point()
